-- MySQL Script generated by MySQL Workbench
-- 10/15/16 10:55:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hh_guts_public
-- -----------------------------------------------------
-- public facing schema
DROP SCHEMA IF EXISTS `hh_guts_public` ;

-- -----------------------------------------------------
-- Schema hh_guts_public
--
-- public facing schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hh_guts_public` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `hh_guts_public` ;

-- -----------------------------------------------------
-- Table `hh_guts_public`.`tResponder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hh_guts_public`.`tResponder` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hh_guts_public`.`tResponder` (
  `idResponder` VARCHAR(45) NULL,
  PRIMARY KEY (`idResponder`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idtResponder_UNIQUE` ON `hh_guts_public`.`tResponder` (`idResponder` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hh_guts_public`.`tSurveyRes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hh_guts_public`.`tSurveyRes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hh_guts_public`.`tSurveyRes` (
  `idResponder` VARCHAR(45) NOT NULL,
  `dtSubmit` DATETIME NOT NULL DEFAULT now(),
  `genWellbeing` INT(1) NULL,
  `abdPain` INT(1) NULL,
  `lqdStoolFreq` INT(10) NULL,
  `adbMass` INT(1) NULL,
  `jointProb` INT(1) NULL,
  `eyeProb` INT(1) NULL,
  `mouthProb` INT(1) NULL,
  `skinProbUlcers` INT(1) NULL,
  `skinProbRedBumps` INT(1) NULL,
  `perianalProb` INT(1) NULL,
  `fistula` INT(1) NULL,
  PRIMARY KEY (`idResponder`, `dtSubmit`),
  CONSTRAINT `responder`
    FOREIGN KEY (`idResponder`)
    REFERENCES `hh_guts_public`.`tResponder` (`idResponder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hh_guts_public`.`tIBDocReading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hh_guts_public`.`tIBDocReading` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hh_guts_public`.`tIBDocReading` (
  `idResponder` VARCHAR(45) NOT NULL,
  `Reading` VARCHAR(45) NOT NULL,
  `dtSubmit` DATETIME NOT NULL,
  PRIMARY KEY (`idResponder`, `dtSubmit`),
  CONSTRAINT `RespReading`
    FOREIGN KEY (`idResponder`)
    REFERENCES `hh_guts_public`.`tResponder` (`idResponder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
GRANT SELECT, INSERT, TRIGGER ON TABLE `hh_guts_public`.* TO 'hh16';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
